SERVER_PORT: 8080
JWT_SIGNATURE: my_secret_key
POSTGRES_USER: user
POSTGRES_PASSWORD: password
POSTGRES_DB: pvz_db
POSTGRES_PORT: 5432
POSTGRES_HOST: db
MIGRATIONS_PATH: file://db/migrations
JWT_TOKEN_LIFESPAN: 24h