// Code generated by MockGen. DO NOT EDIT.
// Source: reception.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/nik-mLb/avito_task/internal/models/reception"
)

// MockReceptionUsecase is a mock of ReceptionUsecase interface.
type MockReceptionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockReceptionUsecaseMockRecorder
}

// MockReceptionUsecaseMockRecorder is the mock recorder for MockReceptionUsecase.
type MockReceptionUsecaseMockRecorder struct {
	mock *MockReceptionUsecase
}

// NewMockReceptionUsecase creates a new mock instance.
func NewMockReceptionUsecase(ctrl *gomock.Controller) *MockReceptionUsecase {
	mock := &MockReceptionUsecase{ctrl: ctrl}
	mock.recorder = &MockReceptionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceptionUsecase) EXPECT() *MockReceptionUsecaseMockRecorder {
	return m.recorder
}

// CloseReception mocks base method.
func (m *MockReceptionUsecase) CloseReception(ctx context.Context, pvzID string) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseReception indicates an expected call of CloseReception.
func (mr *MockReceptionUsecaseMockRecorder) CloseReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseReception", reflect.TypeOf((*MockReceptionUsecase)(nil).CloseReception), ctx, pvzID)
}

// CreateReception mocks base method.
func (m *MockReceptionUsecase) CreateReception(ctx context.Context, pvzID string) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReception indicates an expected call of CreateReception.
func (mr *MockReceptionUsecaseMockRecorder) CreateReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReception", reflect.TypeOf((*MockReceptionUsecase)(nil).CreateReception), ctx, pvzID)
}
